//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialEvents.Service.SacabServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserApplicationRoles", Namespace="http://schemas.datacontract.org/2004/07/SacabWcfService")]
    [System.SerializableAttribute()]
    public partial class UserApplicationRoles : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityRoleCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((this.ApplicationIdField.Equals(value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityRoleCode {
            get {
                return this.SecurityRoleCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityRoleCodeField, value) != true)) {
                    this.SecurityRoleCodeField = value;
                    this.RaisePropertyChanged("SecurityRoleCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SacabServiceRef.ISacabService")]
    public interface ISacabService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISacabService/GetUserRolesByAppIdAndUserName_Development", ReplyAction="http://tempuri.org/ISacabService/GetUserRolesByAppIdAndUserName_DevelopmentRespon" +
            "se")]
        System.Collections.Generic.List<SocialEvents.Service.SacabServiceRef.UserApplicationRoles> GetUserRolesByAppIdAndUserName_Development(int appId, string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISacabService/GetUserRolesByAppIdAndUserName_Production", ReplyAction="http://tempuri.org/ISacabService/GetUserRolesByAppIdAndUserName_ProductionRespons" +
            "e")]
        System.Collections.Generic.List<SocialEvents.Service.SacabServiceRef.UserApplicationRoles> GetUserRolesByAppIdAndUserName_Production(int appId, string userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISacabServiceChannel : SocialEvents.Service.SacabServiceRef.ISacabService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SacabServiceClient : System.ServiceModel.ClientBase<SocialEvents.Service.SacabServiceRef.ISacabService>, SocialEvents.Service.SacabServiceRef.ISacabService {
        
        public SacabServiceClient() {
        }
        
        public SacabServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SacabServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SacabServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SacabServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<SocialEvents.Service.SacabServiceRef.UserApplicationRoles> GetUserRolesByAppIdAndUserName_Development(int appId, string userName) {
            return base.Channel.GetUserRolesByAppIdAndUserName_Development(appId, userName);
        }
        
        public System.Collections.Generic.List<SocialEvents.Service.SacabServiceRef.UserApplicationRoles> GetUserRolesByAppIdAndUserName_Production(int appId, string userName) {
            return base.Channel.GetUserRolesByAppIdAndUserName_Production(appId, userName);
        }
    }
}
